/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./components/**/*.{js,jsx,ts,tsx}', './app/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        canvas: '#faf9f5',
        'surface-soft': '#f5f0e8',
        'surface-card': '#efe9de',
        'surface-cream-strong': '#e8e0d2',
        'surface-dark': '#181715',
        'surface-dark-elevated': '#252320',
        'surface-dark-soft': '#1f1e1b',
        ink: '#141413',
        body: '#3d3d3a',
        'body-strong': '#252523',
        muted: '#6c6a64',
        'muted-soft': '#8e8b82',
        hairline: '#e6dfd8',
        'hairline-soft': '#ebe6df',
        primary: {
          DEFAULT: '#cc785c',
          active: '#a9583e',
          disabled: '#e6dfd8',
          foreground: '#ffffff',
        },
        'on-dark': '#faf9f5',
        'on-dark-soft': '#a09d96',
        'accent-teal': '#5db8a6',
        'accent-amber': '#e8a55a',
        success: '#5db872',
        warning: '#d4a017',
        error: '#c64545',
      },
      fontFamily: {
        display: ['CrimsonPro_400Regular'],
        'display-regular': ['CrimsonPro_400Regular'],
        body: ['Inter_400Regular'],
        'body-medium': ['Inter_500Medium'],
        'body-semibold': ['Inter_600SemiBold'],
        'body-bold': ['Inter_700Bold'],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        pill: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.05', letterSpacing: '-1.5px' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-1px' }],
        'display-md': ['36px', { lineHeight: '1.15', letterSpacing: '-0.5px' }],
        'display-sm': ['28px', { lineHeight: '1.2', letterSpacing: '-0.3px' }],
        'title-lg': ['22px', { lineHeight: '1.3', letterSpacing: '0px' }],
        'title-md': ['18px', { lineHeight: '1.4', letterSpacing: '0px' }],
        'title-sm': ['16px', { lineHeight: '1.4', letterSpacing: '0px' }],
        'body-md': ['16px', { lineHeight: '1.55', letterSpacing: '0px' }],
        'body-sm': ['14px', { lineHeight: '1.55', letterSpacing: '0px' }],
        caption: ['13px', { lineHeight: '1.4', letterSpacing: '0px' }],
        'caption-uppercase': ['12px', { lineHeight: '1.4', letterSpacing: '1.5px' }],
        button: ['14px', { lineHeight: '1', letterSpacing: '0px' }],
        'nav-link': ['14px', { lineHeight: '1.4', letterSpacing: '0px' }],
      },
      lineHeight: {
        tight: '1.05',
        snug: '1.1',
        normal: '1.55',
      },
    },
  },
  plugins: [],
}
